//ts-ignore
import * as GeistFont from "geist/font";
import { GeistSans } from "geist/font/sans";

import { AppHeader } from "#components/header/app-header";
import { Providers } from "#components/providers/providers";
import { AppSidebarWithData } from "#components/sidebar/sidebar-data-provider";
import { SidebarInset } from "@repo/ui/components/sidebar";
import { cn } from "@repo/ui/lib/utils";
import type { Metadata } from "next";
import { Suspense } from "react";
import { DataFetcher } from "#components/providers/data-fetcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>{/* <meta http-equiv="Content-Security-Policy" content="default-src 'self'" /> */}</head>
      <body
        id={"root"}
        className={cn(
          "bg-background min-h-svh loading overscroll-none font-sans antialiased",
          // @ts-ignore: Testing invalid input
          GeistFont.GeistSans.className,
          // @ts-ignore: Testing invalid input
          GeistFont.GeistMono.className
        )}
      >
        <Suspense fallback="Loading...">
          <DataFetcher />
          <Providers>
            <AppSidebarWithData />
            <SidebarInset>
              <AppHeader />
              {children}
            </SidebarInset>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}

export const ErrorComponent = () => {
  return <h1>Error</h1>;
};
