//ts-ignore
import { AppHeader } from "@/components/header/app-header";
import { Providers } from "@/components/providers/providers";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
// import { AppSidebarWithData } from "@/components/sidebar/sidebar-data-provider";
import { DataFetcher } from "@/components/providers/data-fetcher";
import { SidebarInset } from "@repo/ui/components/sidebar";
import { cn } from "@repo/ui/lib/utils";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>{/* <meta http-equiv="Content-Security-Policy" content="default-src 'self'" /> */}</head>
      <body
        id={"root"}
        className={cn(
          "bg-background min-h-svh loading overscroll-none font-sans antialiased",
          // @ts-ignore: Testing invalid input
          GeistSans.className,
          // @ts-ignore: Testing invalid input
          GeistMono.className
        )}
      >
        <Suspense fallback="Loading...">
          <DataFetcher />
          <Providers>
            <AppSidebar />
            <SidebarInset>
              <AppHeader />
              {children}
            </SidebarInset>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}

export const ErrorComponent = () => {
  return <h1>Error</h1>;
};
